
spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      encoding: UTF-8
      mode: always
      data-locations: classpath:sql/data.sql

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

server:
  port: 8080

logging:
  file:
    name: './log/app.log'
  level:
    root: info
    org.hibernate.SQL: debug
  logback:
    rollingpolicy:
      file-name-pattern: "./log/%d{yyyy-MM-dd}_%i.log"
      max-history: 30
      max-file-size: 10MB